// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy2jijk5yUIjKXOewQKsZu9Khb-geO0g4',
    appId: '1:20860095519:web:99e32a2e20c716829e192a',
    messagingSenderId: '20860095519',
    projectId: 'codehallam-app',
    authDomain: 'codehallam-app.firebaseapp.com',
    storageBucket: 'codehallam-app.firebasestorage.app',
    measurementId: 'G-W5TTFC7LQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7xPl3t_rweRTuI0KzqsuPzx8aPsMaUG4',
    appId: '1:20860095519:android:0d3024d7a4a0adce9e192a',
    messagingSenderId: '20860095519',
    projectId: 'codehallam-app',
    storageBucket: 'codehallam-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf5kXfqrlVy3DKSX3e-3X31n39lsR0jjM',
    appId: '1:20860095519:ios:ad48fc19f45066269e192a',
    messagingSenderId: '20860095519',
    projectId: 'codehallam-app',
    storageBucket: 'codehallam-app.firebasestorage.app',
    iosBundleId: 'com.example.codehallam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf5kXfqrlVy3DKSX3e-3X31n39lsR0jjM',
    appId: '1:20860095519:ios:ad48fc19f45066269e192a',
    messagingSenderId: '20860095519',
    projectId: 'codehallam-app',
    storageBucket: 'codehallam-app.firebasestorage.app',
    iosBundleId: 'com.example.codehallam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy2jijk5yUIjKXOewQKsZu9Khb-geO0g4',
    appId: '1:20860095519:web:5d0306a805e271189e192a',
    messagingSenderId: '20860095519',
    projectId: 'codehallam-app',
    authDomain: 'codehallam-app.firebaseapp.com',
    storageBucket: 'codehallam-app.firebasestorage.app',
    measurementId: 'G-DTL2RWGTZY',
  );
}
